# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdf29fc26f949ef6d3001b91b62b0ae0fae6be7a1f15c588234504865ad8c6ba987006a2fbb1647131c8d3a8b753e7372733058e0a95ba4231e99b905472fa96

test:
  secret_key_base: 95ae55ca56f50125809d9f9e627eed6c9f8a01a98aa86532eaf7e97ff33da1f151d8c3b6d2eceace76358c0b11a8ca0f7070e72fb24bc6282a9784c833056f5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
